global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'healthcare-pipeline'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    metric_relabel_configs:
      - source_labels: [endpoint]
        target_label: api_endpoint
        
  - job_name: 'patient-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/data/stats'
    scrape_interval: 10s

  - job_name: 'system-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s